### ISSUE TITLE
[BUG]: Pimcore Datahub File Exporter bundle not exporting data with configured languages

### ISSUE THREAD

**Issue by coes-devs-jakala** [pimcore/data-hub#827] opened 2024-01-13 15:49 UTC
### Expected behavior

Using the Datahub File Exporter Bundle, setting up a JOB with localized fields and a language different from the system default language, the Dataobject data should be exported translated to the configured language.

The configuration is saved correctly, with the configured language and fields.

### Actual behavior

The exported uses only the default system language provided inside the platform settings.

### Steps to reproduce

1. Create an export JOB for a Dataobject containing localized fields
2. Configure the Schema to export the localized fiels
3. Set a language different from the default system language inside the Schema configuration
4. Run the export

**Comment by ghost** [comment] 2024-01-16 08:22
@coes-devs-jakala This seems to be a duplicate of your reported issue in our enterprise portal and which I opened here: https://github.com/pimcore/data-hub-file-export/issues/151
Can we close this one?

**Comment by coes-devs-jakala** [comment] 2024-01-16 08:26
> @coes-devs-jakala This seems to be a duplicate of your reported issue in our enterprise portal and which I opened here: [pimcore/data-hub-file-export#151](https://github.com/pimcore/data-hub-file-export/issues/151) Can we close this one?

@wisconaut yes go on please, thank you

**Comment by kingjia90** [comment] 2024-01-16 15:50
Fixed by https://github.com/pimcore/pimcore/pull/16469 (`v11.1.5`)

**Closed as completed by kingjia90** 2024-01-16 15:50 UTC
Labels: Bug
