### ISSUE TITLE
[Bug]: GraphQL ignores model-overrides

### ISSUE THREAD

**Issue by florian25686** [pimcore/data-hub#488] opened 2022-03-03 10:47 UTC
### Expected behavior

GraphQL interfaces are using the model-overrides as the rest of pimcore does

### Actual behavior

GraphQL ignores the overwrites and just loads the data models

### Steps to reproduce

In the Pimcore demo the config file for ecommerce overwrites some dataobject classes:

    pimcore:
        models:
            class_overrides:
                Pimcore\Model\DataObject\Car: App\Model\Product\Car
                Pimcore\Model\DataObject\AccessoryPart: App\Model\Product\AccessoryPart
                Pimcore\Model\DataObject\Category: App\Model\Product\Category

- Go in the `App\Model\Product\Car`-Class and set a debugger break point in `function getOSName()` 
- Load a car product page `http://pimcore_test.local:8083/en/shop/Products/Cars/VW-Type-2~p235` for example
- This will load `App\Model\Product\Car`

Now do the same with the default graphql endpoint
- Set a breakpoint in `Pimcore\Model\DataObject\Car` in `function getName()`
- Go in the `App\Model\Product\Car`-Class and set a debugger break point in `function getOSName()`
- Load data via graphql
It will go straight into the `Pimcore\Model\DataObject\Car` instead of `App\Model\Product\Car`

**Comment by mcop1** [comment] 2022-03-17 12:51
@florian25686 GraphQL respects the overrides/mapped classes. But you are able to query the properties defined in the schema-configuration only. 

As solution to this might be to add a calculated field:
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/89011527/158810225-d8736efc-7a55-407d-b18a-1b66aba4a3aa.png)

And add the calculated field to your GraphQL query:

`{
  getCar(id:81) 
  {    
		name,
    calc
  }
}`

Since this is not a bug I am going to close the issue. If you have any further questions feel free to open another issue.
Thanks you and best regards

**Closed as completed by mcop1** 2022-03-17 12:51 UTC
Labels: Bug
