### ISSUE TITLE
[Bug]: Cors Error when APP_DEBUG=0

### ISSUE THREAD

**Issue by snmabaur** [pimcore/data-hub#655] opened 2022-12-20 14:59 UTC
### Actual behavior

As soon as I set the .env variable `APP_DEBUG` to `0` or `false` I get a CORS error and also the GraphiQL explorer from the backend doesn't work anymore. With `APP_DEBUG` `1` or `true` it work's well. 

Now the problem is that Pimcore gicves a notification that Debug Mode is activated and since it's a production ready page we don't want to let it run in Debug Mode

### Steps to reproduce

Set `APP_DEBUG` in .env to `false` or `true`

**Comment by mcop1** [comment] 2023-01-02 14:49
Hello @snmabaur ,

sorry, but I wasn´t able to reproduce your problem with the latest 1.5.2 patch. Which version are you using?

**Comment by snmabaur** [comment] 2023-01-10 10:14
Hi

sorrry for the late answer... I was using 1.5.2 and now with 1.5.3 I have the same problem

**Comment by mcop1** [comment] 2023-02-15 08:06
Sorry, I am still not able to reproduce the problem

![grafik](https://user-images.githubusercontent.com/89011527/218968289-1ab6a03f-30d5-4ceb-88cc-6638d003fe9e.png)

but still everything is working as expected

![grafik](https://user-images.githubusercontent.com/89011527/218968535-fb9c0aa4-17ce-4b19-9552-ef4ba0520c2b.png)

I´ll close the issue for now, please feel free to reopen it once you have any further information. Thank you!

**Closed as completed by mcop1** 2023-02-15 08:06 UTC
Labels: Bug
